export const GalleryImage = [

    "https://drive.google.com/file/d/1C1L5gmDS3L9OuQpbagyQ4k8NBEqylcWW/view?usp=sharing",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",
    // "https://drive.google.com/drive/folders/1vy9kJj26uKwpgTO7Pe4ewZabikgWB0DE",  
];